version: '3.8'

services:
  # Next.js Frontend Service - connects to existing API container
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - API_URL=http://pegasus-nest-prod:3000
    image: pegasus-frontend:latest
    container_name: pegasus-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - API_URL=http://pegasus-nest-prod:3000
      - PORT=3001
      - HOSTNAME=0.0.0.0
    external_links:
      - pegasus-nest-prod:pegasus-nest-prod
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs:rw
